import type { Video } from "@/types";

export const mockVideos: Video[] = [
  // 🔥 AI 트렌드 (4개)
  {
    id: "1",
    title: "GPT-5 출시 임박? 2025년 AI 트렌드 전망",
    description:
      "2025년 하반기 AI 업계에서 예상되는 주요 변화와 GPT-5 관련 루머를 분석합니다.",
    youtubeUrl: "https://youtube.com/watch?v=example1",
    thumbnailUrl: "https://picsum.photos/seed/aitube1/480/270",
    channelName: "테크 인사이드",
    publishedAt: "2025-04-22T08:00:00Z",
    viewCount: 567000,
    duration: "18:45",
    category: "ai-trend",
    difficulty: "beginner",
    language: "ko",
    tags: ["GPT-5", "AI트렌드", "2025"],
  },
  {
    id: "2",
    title: "Claude 4 vs GPT-5: The Ultimate Comparison",
    description:
      "An in-depth comparison of the two most powerful AI models of 2025 across various benchmarks and real-world tasks.",
    youtubeUrl: "https://youtube.com/watch?v=example2",
    thumbnailUrl: "https://picsum.photos/seed/aitube2/480/270",
    channelName: "AI Explained",
    publishedAt: "2025-04-25T07:00:00Z",
    viewCount: 890000,
    duration: "32:10",
    category: "ai-trend",
    difficulty: "beginner",
    language: "en",
    tags: ["Claude", "GPT-5", "비교"],
  },
  {
    id: "3",
    title: "애플 AI 전략 총정리: 시리가 달라진다",
    description:
      "WWDC 2025에서 발표된 애플의 AI 전략과 시리의 대규모 업그레이드를 분석합니다.",
    youtubeUrl: "https://youtube.com/watch?v=example3",
    thumbnailUrl: "https://picsum.photos/seed/aitube3/480/270",
    channelName: "테크읽어주는남자",
    publishedAt: "2025-04-18T14:00:00Z",
    viewCount: 234000,
    duration: "22:15",
    category: "ai-trend",
    difficulty: "beginner",
    language: "ko",
    tags: ["애플", "시리", "AI전략"],
  },
  {
    id: "4",
    title: "오픈소스 vs 클로즈드 AI 모델: 누가 이기나?",
    description:
      "Llama 4, Mistral, GPT-5 등 오픈소스와 클로즈드 모델의 성능 격차 분석 및 전망",
    youtubeUrl: "https://youtube.com/watch?v=example4",
    thumbnailUrl: "https://picsum.photos/seed/aitube4/480/270",
    channelName: "AI 디코드",
    publishedAt: "2025-04-10T16:00:00Z",
    viewCount: 178000,
    duration: "25:30",
    category: "ai-trend",
    difficulty: "intermediate",
    language: "ko",
    tags: ["오픈소스", "Llama", "모델비교"],
  },
  // 🔧 AI 활용 (4개)
  {
    id: "5",
    title: "비개발자를 위한 ChatGPT 업무 활용법 10가지",
    description:
      "ChatGPT를 200% 활용하기 위한 프롬프트 작성 기법을 초보자도 쉽게 따라할 수 있도록 정리했습니다.",
    youtubeUrl: "https://youtube.com/watch?v=example5",
    thumbnailUrl: "https://picsum.photos/seed/aitube5/480/270",
    channelName: "AI 마스터",
    publishedAt: "2025-04-20T09:00:00Z",
    viewCount: 125000,
    duration: "15:30",
    category: "ai-usage",
    difficulty: "beginner",
    language: "ko",
    tags: ["ChatGPT", "업무활용", "프롬프트"],
  },
  {
    id: "6",
    title: "Cursor AI로 풀스택 앱 하루 만에 만들기",
    description:
      "AI 코딩 어시스턴트 Cursor를 활용해 실제 서비스 가능한 풀스택 웹앱을 하루 만에 개발하는 과정입니다.",
    youtubeUrl: "https://youtube.com/watch?v=example6",
    thumbnailUrl: "https://picsum.photos/seed/aitube6/480/270",
    channelName: "코딩으로 세상을",
    publishedAt: "2025-04-08T12:00:00Z",
    viewCount: 234000,
    duration: "52:00",
    category: "ai-usage",
    difficulty: "intermediate",
    language: "ko",
    tags: ["Cursor", "코딩", "풀스택"],
  },
  {
    id: "7",
    title: "Midjourney V7 새로운 기능 총정리",
    description:
      "Midjourney V7에서 추가된 놀라운 기능들을 실제 예시와 함께 살펴봅니다.",
    youtubeUrl: "https://youtube.com/watch?v=example7",
    thumbnailUrl: "https://picsum.photos/seed/aitube7/480/270",
    channelName: "크리에이티브 AI",
    publishedAt: "2025-04-15T10:00:00Z",
    viewCount: 89000,
    duration: "22:15",
    category: "ai-usage",
    difficulty: "intermediate",
    language: "ko",
    tags: ["Midjourney", "이미지생성", "V7"],
  },
  {
    id: "8",
    title: "AI로 쇼핑몰 매출 3배 올리기 - 실전 사례",
    description:
      "실제 이커머스 비즈니스에 AI를 적용하여 매출을 극적으로 향상시킨 사례를 공유합니다.",
    youtubeUrl: "https://youtube.com/watch?v=example8",
    thumbnailUrl: "https://picsum.photos/seed/aitube8/480/270",
    channelName: "비즈니스 AI",
    publishedAt: "2025-04-01T09:00:00Z",
    viewCount: 45000,
    duration: "28:00",
    category: "ai-usage",
    difficulty: "intermediate",
    language: "ko",
    tags: ["이커머스", "매출", "활용사례"],
  },
  // 📚 AI 학습 (4개)
  {
    id: "9",
    title: "딥러닝 기초: 신경망 이해하기",
    description:
      "딥러닝의 기본 개념부터 신경망 구조까지, 비전공자도 이해할 수 있도록 쉽게 설명합니다.",
    youtubeUrl: "https://youtube.com/watch?v=example9",
    thumbnailUrl: "https://picsum.photos/seed/aitube9/480/270",
    channelName: "AI 캠퍼스",
    publishedAt: "2025-04-12T10:00:00Z",
    viewCount: 312000,
    duration: "35:20",
    category: "ai-learning",
    difficulty: "beginner",
    language: "ko",
    tags: ["딥러닝", "신경망", "기초"],
  },
  {
    id: "10",
    title: "Transformer 아키텍처 논문 완벽 리뷰",
    description:
      '"Attention is All You Need" 논문을 수식 하나하나 짚어가며 완벽하게 이해하는 강의입니다.',
    youtubeUrl: "https://youtube.com/watch?v=example10",
    thumbnailUrl: "https://picsum.photos/seed/aitube10/480/270",
    channelName: "딥러닝 논문읽기",
    publishedAt: "2025-03-28T13:00:00Z",
    viewCount: 445000,
    duration: "1:12:00",
    category: "ai-learning",
    difficulty: "advanced",
    language: "ko",
    tags: ["Transformer", "논문리뷰", "Attention"],
  },
  {
    id: "11",
    title: "LLM Fine-tuning with LoRA: A Complete Tutorial",
    description:
      "Learn how to fine-tune large language models efficiently using LoRA adapters with practical code examples.",
    youtubeUrl: "https://youtube.com/watch?v=example11",
    thumbnailUrl: "https://picsum.photos/seed/aitube11/480/270",
    channelName: "ML Engineering",
    publishedAt: "2025-03-25T17:00:00Z",
    viewCount: 156000,
    duration: "45:00",
    category: "ai-learning",
    difficulty: "advanced",
    language: "en",
    tags: ["LLM", "Fine-tuning", "LoRA"],
  },
  {
    id: "12",
    title: "RAG 파이프라인 실전 구축 가이드",
    description:
      "RAG(Retrieval Augmented Generation)를 활용한 AI 챗봇을 처음부터 구축하는 방법입니다.",
    youtubeUrl: "https://youtube.com/watch?v=example12",
    thumbnailUrl: "https://picsum.photos/seed/aitube12/480/270",
    channelName: "엔터프라이즈 AI",
    publishedAt: "2025-04-05T15:00:00Z",
    viewCount: 67000,
    duration: "1:05:00",
    category: "ai-learning",
    difficulty: "advanced",
    language: "ko",
    tags: ["RAG", "챗봇", "파이프라인"],
  },
];

export const mockCategories = [
  {
    slug: "ai-trend" as const,
    name: "AI 트렌드",
    count: 4,
    icon: "🔥",
  },
  {
    slug: "ai-usage" as const,
    name: "AI 활용",
    count: 4,
    icon: "🔧",
  },
  {
    slug: "ai-learning" as const,
    name: "AI 학습",
    count: 4,
    icon: "📚",
  },
];
