import type { Video } from "@/types";

export const mockVideos: Video[] = [
  {
    id: "1",
    title: "ChatGPT 프롬프트 엔지니어링 완벽 가이드 2025",
    description:
      "ChatGPT를 200% 활용하기 위한 프롬프트 작성 기법을 초보자도 쉽게 따라할 수 있도록 정리했습니다.",
    youtubeUrl: "https://youtube.com/watch?v=example1",
    thumbnailUrl: "https://picsum.photos/seed/aitube1/480/270",
    channelName: "AI 마스터",
    publishedAt: "2025-04-20T09:00:00Z",
    viewCount: 125000,
    duration: "15:30",
    category: "prompt-engineering",
    difficulty: "beginner",
    language: "ko",
    tags: ["ChatGPT", "프롬프트", "입문"],
  },
  {
    id: "2",
    title: "Midjourney V7 새로운 기능 총정리",
    description:
      "Midjourney V7에서 추가된 놀라운 기능들을 실제 예시와 함께 살펴봅니다.",
    youtubeUrl: "https://youtube.com/watch?v=example2",
    thumbnailUrl: "https://picsum.photos/seed/aitube2/480/270",
    channelName: "크리에이티브 AI",
    publishedAt: "2025-04-18T14:00:00Z",
    viewCount: 89000,
    duration: "22:15",
    category: "ai-tools",
    difficulty: "intermediate",
    language: "ko",
    tags: ["Midjourney", "이미지생성", "V7"],
  },
  {
    id: "3",
    title: "LLM Fine-tuning with LoRA: A Complete Tutorial",
    description:
      "Learn how to fine-tune large language models efficiently using LoRA adapters with practical code examples.",
    youtubeUrl: "https://youtube.com/watch?v=example3",
    thumbnailUrl: "https://picsum.photos/seed/aitube3/480/270",
    channelName: "ML Engineering",
    publishedAt: "2025-04-15T11:00:00Z",
    viewCount: 234000,
    duration: "45:00",
    category: "model-dev",
    difficulty: "advanced",
    language: "en",
    tags: ["LLM", "Fine-tuning", "LoRA"],
  },
  {
    id: "4",
    title: "GPT-5 출시 임박? 2025년 AI 트렌드 전망",
    description:
      "2025년 하반기 AI 업계에서 예상되는 주요 변화와 GPT-5 관련 루머를 분석합니다.",
    youtubeUrl: "https://youtube.com/watch?v=example4",
    thumbnailUrl: "https://picsum.photos/seed/aitube4/480/270",
    channelName: "테크 인사이드",
    publishedAt: "2025-04-22T08:00:00Z",
    viewCount: 567000,
    duration: "18:45",
    category: "ai-news",
    difficulty: "beginner",
    language: "ko",
    tags: ["GPT-5", "AI트렌드", "2025"],
  },
  {
    id: "5",
    title: "AI로 쇼핑몰 매출 3배 올리기 - 실전 사례",
    description:
      "실제 이커머스 비즈니스에 AI를 적용하여 매출을 극적으로 향상시킨 사례를 공유합니다.",
    youtubeUrl: "https://youtube.com/watch?v=example5",
    thumbnailUrl: "https://picsum.photos/seed/aitube5/480/270",
    channelName: "비즈니스 AI",
    publishedAt: "2025-04-10T16:00:00Z",
    viewCount: 45000,
    duration: "28:00",
    category: "use-cases",
    difficulty: "intermediate",
    language: "ko",
    tags: ["이커머스", "매출", "활용사례"],
  },
  {
    id: "6",
    title: "Stable Diffusion 3.5 설치부터 활용까지",
    description:
      "로컬 PC에서 Stable Diffusion 3.5를 설치하고 고품질 이미지를 생성하는 전체 과정을 안내합니다.",
    youtubeUrl: "https://youtube.com/watch?v=example6",
    thumbnailUrl: "https://picsum.photos/seed/aitube6/480/270",
    channelName: "AI 아트랩",
    publishedAt: "2025-04-12T10:00:00Z",
    viewCount: 178000,
    duration: "35:20",
    category: "ai-tools",
    difficulty: "intermediate",
    language: "both",
    tags: ["Stable Diffusion", "이미지생성", "로컬설치"],
  },
  {
    id: "7",
    title: "Transformer 아키텍처 논문 완벽 리뷰",
    description:
      '"Attention is All You Need" 논문을 수식 하나하나 짚어가며 완벽하게 이해하는 강의입니다.',
    youtubeUrl: "https://youtube.com/watch?v=example7",
    thumbnailUrl: "https://picsum.photos/seed/aitube7/480/270",
    channelName: "딥러닝 논문읽기",
    publishedAt: "2025-03-28T13:00:00Z",
    viewCount: 312000,
    duration: "1:12:00",
    category: "model-dev",
    difficulty: "advanced",
    language: "ko",
    tags: ["Transformer", "논문리뷰", "Attention"],
  },
  {
    id: "8",
    title: "Claude 4 vs GPT-5: The Ultimate Comparison",
    description:
      "An in-depth comparison of the two most powerful AI models of 2025 across various benchmarks and real-world tasks.",
    youtubeUrl: "https://youtube.com/watch?v=example8",
    thumbnailUrl: "https://picsum.photos/seed/aitube8/480/270",
    channelName: "AI Explained",
    publishedAt: "2025-04-25T07:00:00Z",
    viewCount: 890000,
    duration: "32:10",
    category: "ai-news",
    difficulty: "beginner",
    language: "en",
    tags: ["Claude", "GPT-5", "비교"],
  },
  {
    id: "9",
    title: "Cursor AI로 풀스택 앱 하루 만에 만들기",
    description:
      "AI 코딩 어시스턴트 Cursor를 활용해 실제 서비스 가능한 풀스택 웹앱을 하루 만에 개발하는 과정입니다.",
    youtubeUrl: "https://youtube.com/watch?v=example9",
    thumbnailUrl: "https://picsum.photos/seed/aitube9/480/270",
    channelName: "코딩으로 세상을",
    publishedAt: "2025-04-08T12:00:00Z",
    viewCount: 234000,
    duration: "52:00",
    category: "ai-tools",
    difficulty: "intermediate",
    language: "ko",
    tags: ["Cursor", "코딩", "풀스택"],
  },
  {
    id: "10",
    title: "기업용 AI 챗봇 구축하기 - RAG 파이프라인",
    description:
      "RAG(Retrieval Augmented Generation)를 활용한 기업 맞춤형 AI 챗봇을 처음부터 구축하는 방법입니다.",
    youtubeUrl: "https://youtube.com/watch?v=example10",
    thumbnailUrl: "https://picsum.photos/seed/aitube10/480/270",
    channelName: "엔터프라이즈 AI",
    publishedAt: "2025-04-05T15:00:00Z",
    viewCount: 67000,
    duration: "1:05:00",
    category: "use-cases",
    difficulty: "advanced",
    language: "ko",
    tags: ["RAG", "챗봇", "기업용"],
  },
  {
    id: "11",
    title: "프롬프트 체이닝으로 복잡한 작업 자동화하기",
    description:
      "여러 프롬프트를 연결하여 복잡한 비즈니스 워크플로우를 자동화하는 고급 기법을 소개합니다.",
    youtubeUrl: "https://youtube.com/watch?v=example11",
    thumbnailUrl: "https://picsum.photos/seed/aitube11/480/270",
    channelName: "AI 마스터",
    publishedAt: "2025-04-01T09:00:00Z",
    viewCount: 156000,
    duration: "25:40",
    category: "prompt-engineering",
    difficulty: "advanced",
    language: "ko",
    tags: ["프롬프트체이닝", "자동화", "고급"],
  },
  {
    id: "12",
    title: "Building AI Agents with LangGraph",
    description:
      "A hands-on tutorial on building sophisticated AI agents using LangGraph framework with tool use and memory.",
    youtubeUrl: "https://youtube.com/watch?v=example12",
    thumbnailUrl: "https://picsum.photos/seed/aitube12/480/270",
    channelName: "AI Engineering",
    publishedAt: "2025-03-25T17:00:00Z",
    viewCount: 445000,
    duration: "58:30",
    category: "model-dev",
    difficulty: "advanced",
    language: "en",
    tags: ["LangGraph", "AI Agent", "Framework"],
  },
];

export const mockCategories = [
  {
    slug: "ai-tools" as const,
    name: "AI 도구 활용",
    count: 3,
    icon: "🛠️",
  },
  {
    slug: "prompt-engineering" as const,
    name: "프롬프트 엔지니어링",
    count: 2,
    icon: "💬",
  },
  {
    slug: "model-dev" as const,
    name: "모델 개발/연구",
    count: 3,
    icon: "🧪",
  },
  {
    slug: "ai-news" as const,
    name: "AI 뉴스/트렌드",
    count: 2,
    icon: "📰",
  },
  {
    slug: "use-cases" as const,
    name: "활용 사례",
    count: 2,
    icon: "💡",
  },
];
